services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      -  keycloakpostgress

volumes:
  postgres_data:


networks:
  keycloakpostgress:
    # Use a custom driver
    external: true

