version: '3.7'

services:
  sonarqube:
    image: sonarqube:9.9.1-community  # Replace with desired tag
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      # Replace with environment variables or secrets
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: ${SONARQUBE_JDBC_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs

  postgres:
    image: postgres:15-alpine  # Replace with desired tag
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_logs:
  postgres_data:
