version: "3"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf1:/opt/sonarqube/conf
      - sonarqube_data1:/opt/sonarqube/data
      - sonarqube_extensions1:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins1:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - db
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql1:/var/lib/postgresql
      - postgresql_data1:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf1:
  sonarqube_data1:
  sonarqube_extensions1:
  sonarqube_bundled-plugins1:
  postgresql1:
  postgresql_data1:

