name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: nourchawebi/astonvilla
          tags: |
            type=schedule                # Tag based on scheduled events (if any)
            type=ref,event=branch       # Tag based on branch references
            type=ref,event=pr           # Tag based on pull request references
            type=semver,pattern={{version}}  # Semantic versioning tag
            type=semver,pattern={{major}}.{{minor}} # Major and minor version tag
            type=semver,pattern={{major}}    # Major version tag
            type=sha                    # Tag based on SHA hash of the commit
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: # nourchawebi/astonvilla:
            ${{ steps.meta.outputs.tags }}
