name: Build and Push Docker image to Docker Hub

on: push
#on:
#  push:
#    branches: [ "main" ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nourchawebi/astonvilla:1.1.${{ github.run_number }}
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - name: Run SonarQube server
        run:
          docker-compose -f "sonar-docker-compose.yaml" up -d --build
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Wait for SonarQube to be ready
        run: |
            for i in {1..30}; do
              if curl -s http://localhost:9000/api/system/health | grep -q '"status":"UP"'; then
                echo "SonarQube is up!"
                exit 0
              fi
              echo "Waiting for SonarQube..."
              sleep 10
            done
            echo "SonarQube did not start in time."
            exit 1
      - name: Analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}   # Add the URL of your instance to the variables of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
