name: buildDockerImageARM

# Trigger the workflow on push events to tags that match the pattern "v*.*.*"
on:
  push:
    tags:
      - "v*.*.*"
  # Optionally, uncomment the lines below to trigger the workflow on pull requests to the master branch
  # pull_request:
  #   branches:
  #     - "master"

jobs:
  docker:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/nourchawebi/astonvilla
          tags: |
            type=schedule                # Tag based on scheduled events (if any)
            type=ref,event=branch       # Tag based on branch references
            type=ref,event=pr           # Tag based on pull request references
            type=semver,pattern={{version}}  # Semantic versioning tag
            type=semver,pattern={{major}}.{{minor}} # Major and minor version tag
            type=semver,pattern={{major}}    # Major version tag
            type=sha                    # Tag based on SHA hash of the commit
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'  # Only login if the event is not a pull request
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .                            # Directory containing the Dockerfile and build context
          push: true
          tags: ${{ steps.meta.outputs.tags }}   # Tags generated by the Docker meta action labels: ${{ steps.meta.outputs.labels }}  # Labels generated by the Docker meta action
